version: '2'
services:
  # Auto generates the properties files for all services and the nginx config
  configs:
    environment:
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    image: python:2.7
    entrypoint: /entrypoint.sh
    volumes:
      - .:/code
      - ./docker/entrypoints/configs.sh:/entrypoint.sh
      - configs-vol:/configs
      - $HOME/.aws/:/root/.aws:ro
      - $HOME/.gu/grid/:/root/.gu/grid

  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile-elastic
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./docker/configs/elasticsearch:/usr/share/elasticsearch/config"
      - "./docker/data/elasticsearch:/usr/share/elasticsearch/data"
    restart: unless-stopped

  media-api:
    environment:
      APP: media-api
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
      - elasticsearch
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  thrall:
    environment:
      APP: thrall
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
      - elasticsearch
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  image-loader:
    environment:
      APP: image-loader
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  kahuna:
    environment:
      APP: kahuna
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  cropper:
    environment:
      APP: cropper
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  metadata-editor:
    environment:
      APP: metadata-editor
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  usage:
    environment:
      APP: usage
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  collections:
    environment:
      APP: collections
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt
  auth:
    environment:
      APP: auth
      PANDA_BUCKET_NAME: 'grid-panda-goodeggs-dev'
    extends:
      file: ./docker/docker-compose-sbt.yml
      service: sbt
    depends_on:
      - configs
    volumes:
      - configs-vol:/configs
      - ivy-vol:/root/.ivy2
      - sbt-vol:/root/.sbt

  imgops:
    build:
      context: ./docker
      dockerfile: Dockerfile-imgops
    depends_on:
      - configs
    entrypoint: /entrypoint.sh
    volumes:
      - ./docker/entrypoints/imgops.sh:/entrypoint.sh
      - configs-vol:/configs

  # Proxy server for all services
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - elasticsearch
      - configs
      - media-api
      - thrall
      - image-loader
      - kahuna
      - cropper
      - metadata-editor
      - usage
      - collections
      - auth
      - imgops
    entrypoint: /entrypoint.sh
    volumes:
      - configs-vol:/configs
      - ./docker/entrypoints/nginx.sh:/entrypoint.sh

volumes:
  configs-vol:
    driver: local
  ivy-vol:
    driver: local
  sbt-vol:
    driver: local
